@startuml
actor Customer
participant AirlineWebsite
participant BookingAPI
database FlightsDatabase
Customer -> AirlineWebsite: enter booking reference 
Customer -> AirlineWebsite: enter last name
AirlineWebsite -> AirlineWebsite: validate input
AirlineWebsite -> BookingAPI: retrieve booked flights
BookingAPI -> FlightsDatabase: locateCustomerFlight(refNumb, from, to, dates. numPax)
FlightsDatabase --> BookingAPI: matching flight reference number
BookingAPI --> AirlineWebsite: matching flight reference number
AirlineWebsite --> Customer: matching flight reference number
@enduml