' To hire a scooter, a user must download the Electric Scooter Hire app and register their details
' Only users 18 years and above can ride a scooter
' Scooters are rented from charging stations
' There are multiple charging stations in the city
' Only fully charged scooters can be rented
' A scooter must be returned to a charging station
' It takes 2 hours to fully charge a scooter from empty
' Payment is taken once the user has returned their scooter
' A scooter can be marked by a user as broken. This must remove the scooter from a list of available scooters and trigger maintenance personnel to repair the scooter
' The maximum range of a fully charged scooter is 32 km

' A UML Sequence diagram showing the interactions between the user Actor, the Scooter Actor and the classes in the system

@startuml
actor User
participant Hire
participant Scooter
database ChargingLocations
participant MaintenancePersonnel
User -> Hire: input age
User -> Hire: input credit card details
User -> Hire: request scooter
Hire -> Hire: check user's age and credit card details
Hire -> Scooter: get scooter location and availability
Scooter -> Hire: return scooter location and availability
Hire -> User: unlock scooter

User -> Hire: return scooter
Hire -> Scooter: get scooter location
Scooter -> Hire: return scooter location
Hire -> ChargingLocations: check location matches with a charging station
ChargingLocations -> Hire: return matching location
Hire -> Hire: calculate distance travelled
Hire -> User: request pay
User -> Hire: payment
Hire -> Scooter: lock scooter

User -> Hire: flag scooter as broken 
Hire -> Scooter: flag scooter as broken 
Scooter -> MaintenancePersonnel: send location to maintenance 
MaintenancePersonnel -> Scooter: fix scooter


@enduml